### ISSUE TITLE
Can you provide a compiled hpi?

### ISSUE THREAD

**Issue by ev-psaad** [glevy/tfs-plugin#1]
Pretty please, I am a .NET developer historically.

**Comment by bozood** [comment]
> Pretty please, I am a .NET developer historically.

Hi Philip Saad,
Did you manage to generate a .hpi? 
(We have the same concern :( )

**Comment by glevy** [comment]
Here you go
https://github.com/glevy/tfs-plugin/releases/tag/commons-digester2

**Comment by bozood** [comment]
> Here you go https://github.com/glevy/tfs-plugin/releases/tag/commons-digester2

Big thanks!
You saved my day ;)
